### ISSUE TITLE
Header passthrough

### ISSUE THREAD

**Issue by alpox** [ieahleen/habitican-randomizer#25]
Passing headers into a function like `randomAnimals` is heavily confusing. Such functions shouldn't have to care about some headers as their scope doesn't explicitely have to do with requests even if they issue some to do their work.

The headers can be defined globally just fine - or directly in a custom fetch function as hinted in https://github.com/ieahleen/habitican-randomizer/issues/24. This would also allow to define the base for the request so wherever you call the api you only have to e.g.:
``await fetchApi(`/user/equip/${type}/${key}`, ), { method: 'POST' })``

**Comment by ieahleen** [comment]
I don't know if I know how to do this, considering the headers come from user input...

**Comment by ieahleen** [comment]
ok, _globally_

**Comment by alpox** [comment]
As one user only seems to have one setting for the headers its possible to initialize them globally only partially and fill them in with user input later. After that the global headers can be used as they are fully provided.
