### ISSUE TITLE
Keyboard interaction on Form

### ISSUE THREAD

**Issue by alpox** [ieahleen/habitican-randomizer#31]
https://github.com/ieahleen/habitican-randomizer/blob/d0b6954c454c1263ec2cc2c2d7fa000e04a93110/index.html#L17-L25

If you put these fields into a `<form>` element and make the button a submit button: `<input type="submit"` or `<button type="submit"` and then use the `submit` event with `e.preventDefault` instead of `click` you get the same behavior + pressing `Enter` even in the form fields starts working for submitting the form / executing the button-action.

**Comment by ieahleen** [comment]
I really want to make this work, but with a `type="submit"` button, nothing happens anymore, even with `e.preventDefault`. It reloads the page anyway.
The console.log in the addEventListener callback is non responsive.

``` html
        <form class="wrapper">
            <fieldset>
                <label for="UUID">UUID</label>
                <input id="UUID" type="text" placeholder="your UUID">
            </fieldset>
            <fieldset>
                <label for="api-key">API key</label>
                <input id="api-key" type="password" placeholder="your API key">
            </fieldset>
            <input id="submit-api-key" type="submit" value="load user data">
          </form>
```

``` javascript
console.log("why???")
document.getElementById('submit-api-key').addEventListener('submit', (e) => {
  console.log("whyyyyyyyyyy??")
  e.preventDefault();
  e.stopImmediatePropagation();
  build();
});
```

**Comment by ieahleen** [comment]
ok, I put the event listener on the form, it was easier than I was making it to be :+1:
