### ISSUE TITLE
New design

### ISSUE THREAD

**Issue by ieahleen** [ieahleen/habitican-randomizer#34]
It has to follow [Habitica rules](https://habitica.fandom.com/wiki/Guidance_for_Comrades#Rules_for_Third-Party_Tools), but I would like to have something more modern and less white. Though I like the cards thing.

**Comment by nebocoder** [comment]
Hello! I can help refresh the design. I'll make sure to follow the rules. 😊

**Comment by ieahleen** [comment]
hey there @nebocoder, thank you!
for the PR, you can create a new folder in the repo with your design
If you have questions or need help you can join this discord server: https://discord.gg/XBPtqNvv
