### ISSUE TITLE
Refactor: modules

### ISSUE THREAD

**Issue by ieahleen** [ieahleen/habitican-randomizer#35]
Each function should be moved to a single file, and use imports/exports

each can be done separately

 - [ ] `randomAnimals`
 - [ ] `randomTransformationItem`
 - [ ] `buyRandomEquipment`
 - [ ] `randomBackground`
 - [ ] `startRandomQuest`
 - [ ] `equipRandomEquipment`
 - [ ] `utils` file with `randomElementFromArray`, `fetchAPI`, `equipItem`, `castSkill`

**Comment by BasedBrenden** [comment]
Hi, I'd be down to help out with this one if help is still needed!

**Comment by ieahleen** [comment]
hey there @BasedBrenden , yes, sure, go for it!
If you have questions or need help you can join this discord server: https://discord.gg/XBPtqNvv
