### ISSUE TITLE
Form validation when users input UUID and API key

### ISSUE THREAD

**Issue by Rohan-Hazari** [ieahleen/habitican-randomizer#39]
When we click load user data it does not check whether the user has given any input or not it simply moves to show loading
We could show a warning to the user that the input field is empty and that they have to fill it

**Comment by ieahleen** [comment]
Thank you for the Issue!
I think it needs to be like this:
 - check that the fields have the right number of characters inside (for now, not empty, I am checking for lengths requirements)
 - it has only valid characters, so `0-9`, `a-f`, and dash `-` — uppercase or lowercase

And if the API returns an error it should be shown to the user and stop everything else.

**Comment by nibih** [comment]
mind if i tackle this one?

**Comment by ieahleen** [comment]
Sure, @nibih , go for it! 
If you have questions or need help you can join this discord server: https://discord.gg/XBPtqNvv
