### ISSUE TITLE
Show API errors to user

### ISSUE THREAD

**Issue by ieahleen** [ieahleen/habitican-randomizer#40]
When the user submit UUID and API key, it can fail.

If the API call fails, show an error to the user in the form page, do not build the new page.

**Comment by meetagrawal09** [comment]
@ieahleen, I would like to work on this issue. Can you please assign it to me

**Comment by ieahleen** [comment]
Sure, @meetagrawal09!

If you have questions or need help you can join this discord server: https://discord.gg/XBPtqNvv

**Comment by meetagrawal09** [comment]
<img width="122" alt="image" src="https://user-images.githubusercontent.com/73902874/194065587-cd02b0ef-e7db-47ca-9e27-9a73ce714130.png">

@ieahleen, does this seem fine. Whenever we cannot retrieve user for a provided UUID or API Key this message will display
