### ISSUE TITLE
Bug: While trying to fetch the user a 404 response comes up

### ISSUE THREAD

**Issue by aswinikalyan30** [ieahleen/habitican-randomizer#50]
<img width="1191" alt="image" src="https://user-images.githubusercontent.com/76677408/194349823-0fb61c13-9746-4197-8a45-2927a5bc1e7c.png">

This is the API response:
```{"success":false,"error":"NotAuthorized","message":"Missing authentication headers."}```

I created a new user and used the credentials as per the api settings

**Comment by ieahleen** [comment]
I have reverted the production branch to a working state, the main branch has this issue — the error is somewhere in the last few commits
