### ISSUE TITLE
Add Socalify element to README file and auto contributor addition

### ISSUE THREAD

**Issue by PeritusDeveloper** [ieahleen/habitican-randomizer#55]
### Glimpse
<img width="472" alt="image" src="https://user-images.githubusercontent.com/89828000/194415272-03deee95-ed17-4548-bc35-f9b8ce2910e2.png">

- Acknowledge the contributors by mentioning them in README.md file without actually adding them manually.
- Add the instructions for cloning and making a PR for new contributors
- Add the Copyright logo at end of README file
- Add License to the project

**Comment by ieahleen** [comment]
Thank you for your proposal, I have to refuse
