### ISSUE TITLE
typo-- it says "Numger" instead of "Number"

### ISSUE THREAD

**Issue by ShivSitaram** [ieahleen/habitican-randomizer#59]
In the "equip a random background" section, it says "Random Numger Generator" instead of "Random Number Generator." This is the first issue that I've ever created on GitHub. Let me know if I'm doing it the right way.

BTW I'll be able to fix this error myself... not sure how it would work for you to enable. me to edit the code...

I really appreciate any help on the process!

**Comment by ieahleen** [comment]
Thank you for opening the issue, are you interested in working on this yourself?

**Comment by ShivSitaram** [comment]
I am interested; yes! Thanks! :smiley:

**Comment by ieahleen** [comment]
Sure, go for it

**Comment by ShivSitaram** [comment]
done. opened pr 👍

**Comment by ieahleen** [comment]
Please link the Issue in the PR @ShivSitaram

**Comment by ShivSitaram** [comment]
I'm using [this](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue) to see how to link a PR to the issue, but I'm not able to click on the "development" tab in the right-hand side.

**Comment by ShivSitaram** [comment]
done @ieahleen :)
