### ISSUE TITLE
missing space-- says "admin?Just" instead of "admin? Just"

### ISSUE THREAD

**Issue by ShivSitaram** [ieahleen/habitican-randomizer#60]
This error is in the "Buy Random Equipment from the Market!" section. There is a missing space after the punctuation. I'll be glad to fix this!

**Comment by ieahleen** [comment]
Sure, I will gladly accept your contribution

**Comment by ShivSitaram** [comment]
Thanks. I edited the code, clicked the "save" button. It redirected me to this page: https://github.com/ieahleen/habitican-randomizer/compare/main...ShivSitaram:patch-1 . I'm hoping you can take it from here...? I think you have to merge them. I'm sorry-- I've never done this type of thing before.

**Comment by ieahleen** [comment]
You need to create a PR, otherwise it would just me doing the change

**Comment by ieahleen** [comment]
Please link the issue in the PR

**Comment by ShivSitaram** [comment]
done 👍
